# Generated by Django 3.2.3 on 2021-06-03 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posting',
            old_name='users',
            new_name='user',
        ),
    ]
