# Generated by Django 3.2.3 on 2021-06-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100, null=True, unique=True)),
                ('nick_name', models.CharField(max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'joins',
            },
        ),
    ]
