# Generated by Django 2.2.12 on 2021-05-30 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_phone_number'),
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Posting',
        ),
        migrations.AlterModelTable(
            name='posting',
            table='postingss',
        ),
    ]
