# Generated by Django 2.2.12 on 2021-05-30 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_auto_20210530_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posting',
            old_name='post_time',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='posting',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='posting',
            old_name='txt',
            new_name='text',
        ),
    ]
