# Generated by Django 2.2.12 on 2021-05-30 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_auto_20210530_1515'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='posting',
            table='postings',
        ),
    ]
