# Generated by Django 2.2.12 on 2021-06-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0005_auto_20210531_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='image',
            field=models.CharField(max_length=300),
        ),
    ]
