# Generated by Django 2.2.12 on 2021-06-01 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0006_auto_20210601_1616'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CharTest',
        ),
        migrations.DeleteModel(
            name='IntTest',
        ),
    ]
