# Generated by Django 2.2.12 on 2021-06-01 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0007_auto_20210601_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posting',
            old_name='text',
            new_name='posting_text',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='image',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_image', models.CharField(max_length=300)),
                ('posting_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.Posting')),
            ],
        ),
    ]
