# Generated by Django 2.2.12 on 2021-06-01 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0008_auto_20210601_2041'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table='images',
        ),
    ]
