# Generated by Django 3.2.3 on 2021-05-28 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210528_0717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passward',
            new_name='password',
        ),
    ]
