# Generated by Django 3.2.3 on 2021-06-02 05:34

from django.db import migrations, models
import user.validations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=70, unique=True, validators=[user.validations.validate_email])),
                ('password', models.CharField(max_length=256, validators=[user.validations.validate_password])),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=45, null=True, unique=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
