# Generated by Django 3.2.3 on 2021-05-31 10:35

from django.db import migrations, models
import user.validations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=70, unique=True, validators=[user.validations.validate_email]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256, validators=[user.validations.validate_password]),
        ),
    ]
