# Generated by Django 3.2.3 on 2021-05-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('nickname', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'members',
            },
        ),
    ]
