# Generated by Django 3.2.3 on 2021-05-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=300)),
                ('password', models.CharField(max_length=200)),
                ('phone_num', models.CharField(max_length=15)),
                ('nickname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'signup',
            },
        ),
    ]
