# Generated by Django 3.2.3 on 2021-05-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50, unique=True)),
                ('nickname', models.CharField(max_length=50, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=50, null=True, unique=True)),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
