# Generated by Django 3.2.3 on 2021-06-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=50, null=True, unique=True)),
                ('nickname', models.CharField(max_length=50, null=True, unique=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
