# Generated by Django 3.2.3 on 2021-05-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(default=None, max_length=40, unique=True)),
                ('password', models.CharField(default=None, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('nickname', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
