# Generated by Django 3.2.3 on 2021-05-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128)),
                ('password', models.CharField(max_length=20)),
                ('nickname', models.CharField(blank=True, max_length=20)),
                ('contact', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
