# Generated by Django 3.2.3 on 2021-06-02 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_alter_postingimage_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='posting',
            table='postings',
        ),
    ]
