# Generated by Django 3.2.3 on 2021-05-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=45)),
                ('phone_num', models.CharField(max_length=45, null=True, unique=True)),
                ('nick_name', models.CharField(max_length=45, null=True, unique=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
