# Generated by Django 3.2.3 on 2021-05-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_num',
            field=models.IntegerField(max_length=45, null=True, unique=True),
        ),
    ]
