# Generated by Django 3.2.3 on 2021-05-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_phone_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nick_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_num',
        ),
    ]
