# Generated by Django 3.2.3 on 2021-05-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210527_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=45, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_num',
            field=models.CharField(max_length=45, null=True, unique=True),
        ),
    ]
