# Generated by Django 3.2.3 on 2021-06-02 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dog',
        ),
    ]
