# Generated by Django 3.2.3 on 2021-05-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=45)),
                ('phone_no', models.CharField(max_length=45, unique=True)),
                ('full_nm', models.CharField(max_length=45)),
                ('user_nm', models.CharField(max_length=100, unique=True)),
                ('reg_dte', models.DateTimeField(auto_now_add=True)),
                ('withdraw_dte', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
