# Generated by Django 3.2.3 on 2021-05-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=45)),
                ('phonenumber', models.CharField(max_length=45)),
                ('nickname', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
