# Generated by Django 3.2.3 on 2021-06-03 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0003_auto_20210602_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contensboard', models.TextField(null=True)),
                ('img_url', models.URLField(max_length=4000)),
                ('time', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user')),
            ],
        ),
    ]
