# Generated by Django 3.2.3 on 2021-06-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postboard',
            name='contensboard',
            field=models.TextField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='postboard',
            name='img_url',
            field=models.URLField(max_length=400),
        ),
        migrations.AlterField(
            model_name='postboard',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
