# Generated by Django 3.2.3 on 2021-05-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='number',
            field=models.CharField(max_length=30),
        ),
    ]
