# Generated by Django 3.2.3 on 2021-05-28 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210528_0353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='name',
            new_name='nickname',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='number',
            new_name='phone_number',
        ),
    ]
