# Generated by Django 3.2.3 on 2021-05-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_signup_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='nickname',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='phone_number',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
