# Generated by Django 3.2.3 on 2021-05-28 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210528_0921'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signup',
            new_name='User',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
