# Generated by Django 3.2.3 on 2021-06-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterModelTable(
            name='image',
            table='images',
        ),
    ]
