# Generated by Django 3.2.3 on 2021-05-28 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210528_0340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nicname',
            new_name='nickname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
